export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const OPEN_SIGN_DIALOG = 'OPEN_SIGN_DIALOG';
export const CLOSE_SIGN_DIALOG = 'CLOSE_SIGN_DIALOG';
export const LOGIN_SIGN_DIALOG = 'LOGIN_SIGN_DIALOG';
export const REGISTER_SIGN_DIALOG = 'REGISTER_SIGN_DIALOG';

export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const CART_OPERATION_START = 'CART_OPERATION_START';
export const CART_OPERATION_END = 'CART_OPERATION_END';
export const INCREASE_ITEM = 'INCREASE_ITEM';
export const DECREASE_ITEM = 'DECREASE_ITEM';
export const CALCULATE_TOTAL_PRICE = 'CALCULATE_TOTAL_PRICE';
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';

export const FETCH_RESTAURANT_START = 'FETCH_RESTAURANT_START';
export const FETCH_RESTAURANT_SUCCESS = 'FETCH_RESTAURANT_SUCCESS';
export const FETCH_RESTAURANT_ERROR = 'FETCH_RESTAURANT_ERROR';

export const SET_ADDRESS_DATA = 'SET_ADDRESS_DATA';
export const SET_NOTE_DATA = 'SET_NOTE_DATA';

export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const SET_FILTERED_DISHES = 'SET_FILTERED_DISHES';

export const ADD_DISH_START = 'ADD_DISH_START';
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS';
export const ADD_DISH_ERROR = 'ADD_DISH_ERROR';
export const REMOVE_DISH = 'REMOVE_DISH';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_CATEGORY = 'SET_CATEGORY';

export const SET_ACTIVE_NAV = 'SET_ACTIVE_NAV';

export const SET_UNSELECTED_INGREDIENT = 'SET_UNSELECTED_INGREDIENT';
export const REMOVE_UNSELECTED_INGREDIENTS = 'REMOVE_UNSELECTED_INGREDIENTS';
export const CLEAR_UNSELECTED_INGREDIENTS = 'CLEAR_UNSELECTED_INGREDIENTS';

export const SET_DATE_DATA = 'SET_DATE_DATA';
export const SET_TIME_DATA = 'SET_TIME_DATA';
export const SET_PHONE_DATA = 'SET_PHONE_DATA';
export const SET_NAME_DATA = 'SET_NAME_DATA';
export const SET_PERSON_COUNT_DATA = 'SET_PERSON_COUNT_DATA';

export const SET_PICK_UP_DATE = 'SET_PICK_UP_DATE';
export const SET_PICK_UP_TIME = 'SET_PICK_UP_TIME';

export const DELETE_ORDER = 'DELETE_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const SET_ORDER_OPTION = 'SET_ORDER_OPTION';
export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
export const SET_SORTED_ORDER = 'SET_SORTED_ORDER';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
