import exp from 'constants';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const SET_JWT = 'SET_JWT';

export const OPEN_SIGN_DIALOG = 'OPEN_SIGN_DIALOG';
export const CLOSE_SIGN_DIALOG = 'CLOSE_SIGN_DIALOG';
export const LOGIN_SIGN_DIALOG = 'LOGIN_SIGN_DIALOG';
export const REGISTER_SIGN_DIALOG = 'REGISTER_SIGN_DIALOG';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const CART_OPERATION_START = 'CART_OPERATION_START';
export const CART_OPERATION_END = 'CART_OPERATION_END';
export const INCREASE_ITEM = 'INCREASE_ITEM';
export const DECREASE_ITEM = 'DECREASE_ITEM';
export const CALCULATE_TOTAL_PRICE = 'CALCULATE_TOTAL_PRICE';
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';

export const FETCH_RESTAURANT_START = 'FETCH_RESTAURANT_START';
export const FETCH_RESTAURANT_SUCCESS = 'FETCH_RESTAURANT_SUCCESS';
export const FETCH_RESTAURANT_ERROR = 'FETCH_RESTAURANT_ERROR';

export const SET_ADDRESS_DATA = 'SET_ADDRESS_DATA';
export const SET_NOTE_DATA = 'SET_NOTE_DATA';

export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const SET_FILTERED_DISHES = 'SET_FILTERED_DISHES';
